config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'touka/index' => 'touka#index'
  root 'touka#index'
  
  get 'touka/about' => 'touka#about'
  
  get 'touka/member' => 'touka#member'

  get 'touka/QA' => 'touka#QA'

  get 'touka/contact' => 'touka#contact'

  get 'touka/kyushu_union' => 'touka#kyushu_union'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/touka_controller.rb
class ToukaController < ApplicationController
    def index

    end

    def about

    end

    def member

    end

    def QA

    end

    def contact

    end

    def kyushu_union

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/touka_helper.rb
module ToukaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>福岡大学ポケモンサークル</title>
  <%= favicon_link_tag('favicon.ico') %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>

  <div id="header">
    <h2><%= link_to '福岡大学ポケモンサークル トウカのもり' , root_path%></h2>
  </div>

  <div class="main">
    <div class="top">
      <!-- トウカのもり関係はここ -->
      <h4><strong>サイト案内</strong></h4>
      <ul class="nav-list">
        <li class='normal'>
          <%= link_to 'ホーム' , root_path%>
        </li>
        <li class='normal'>
          <%= link_to 'サークル紹介' , touka_about_path %>
        </li>
        <li class='normal'>
          <%= link_to 'メンバー紹介' , touka_member_path %>
        </li>
        <li class='normal'>
          <%= link_to 'よくあるご質問' , touka_QA_path %>
        </li>
        <li class='normal'>
          <%= link_to '九州ポケサー連盟' , touka_kyushu_union_path %>
        </li>
        <li class='normal'>
          <%= link_to 'お問い合わせ' , touka_contact_path %>
        </li>
      </ul>

      <!-- リンク関係はここ -->
      <h4><strong>外部サイト</strong></h4>
      <ul class="nav-list">
        <li class='normal'>
          <a href="https://twitter.com/fukudai_pokemon" target='_blank' rel='noreferrer noopener'>トウカのもり公式X</a>
        </li>
        <li class='normal'>
          <a href="https://www.instagram.com/toukanomori2016/" target='_blank' rel='noreferrer noopener'>トウカのもり公式Instagram</a>
        </li>
        <li class='normal'>
          <a href="https://toukanomori.hatenablog.com/about" target='_blank' rel='noreferrer noopener'>トウカのもり公式ブログ</a>
        </li>
        <li class='normal'>
          <a href="https://www.pokemon.co.jp/" target='_blank' rel='noreferrer noopener'>ポケットモンスターオフィシャルサイト</a>
        </li>
      </ul>
    </div>

    <div class="bottom">
      <%= yield %>
    </div>
  </div>

  <br>

  <footer>
    <span class="footer-text"> 
      当サイトはリンクフリーとなっています。<br>
      当サイトに関係のないサイトリンクはお断りすることがあります。<br>
      ポケットモンスター・ポケモン・Pokemonは任天堂・クリーチャーズ・ゲームフリークの登録商標です。<br>
      このサイトは個人（福岡大学ポケモンサークル トウカのもり）によるものであり、任天堂・ゲームフリーク・株式会社ポケモンとは無関係です。<br>
      また、当サイトで使用されている写真や絵の転載等はご遠慮いただきますようお願いいたします。 
    </span>

    <div id="copyright">
      Copyright (C) 2016 Pokemon club Fukuoka University all rights reserved.
    </div>
  </footer>
</body>
</html>

app/views/touka/QA.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>よくあるご質問</title>
  <!-- jQuery ライブラリを読み込む -->
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <!-- 期間内にのみ表示するための JavaScript コード -->
  <script>
    $(document).ready(function() {
      var today = new Date();
      var startDate = new Date('2024-01-07'); // 開始日
      var endDate = new Date('2024-04-26');   // 終了日

      if (today >= startDate && today <= endDate) {
        // 期間内の場合、指定の要素を表示
        $(".limited-content").show();
      } else {
        // 期間外の場合、指定の要素を非表示
        $(".limited-content").hide();
      }
    });
  </script>
  <!-- スタイルシートを読み込む（必要に応じて修正）-->
  <%= stylesheet_link_tag 'QA', media: 'all' %>
</head>
<body>

<div class="main-container">
    <div class="page-title">
        <h2><strong>よくあるご質問</strong></h2>
    </div>

    <div class="text">
        <p>
            よくある質問を以下にまとめました！他に何か質問があれば、<strong><%= link_to 'お問い合わせ' , touka_contact_path , class: 'new-event' %></strong>の項目よりご連絡お願いします！
        </p>
    </div>

    <div class="contact-box">
        <h4>Q. 対戦に詳しくないのですが、活動に参加してもよろしいですか？</h4>
    </div>
    <div class="text">
        <p>
            様々なポケモン好きの皆さんを大歓迎しています！対戦に詳しくなくても、対戦知識が全くなくても大丈夫です。大切なのは「ポケモンが好き」という気持ちです！
        </p>
    </div>

    <div class="contact-box">
        <h4>Q. ポケモン以外のゲームやイベントにも参加できるとのことですが、これらの活動はどのように企画されていますか？メンバーのアイデアや提案も取り入れられていますか？</h4>
    </div>
    <div class="text">
        <p>
            活動はメンバーの提案やアイデアを取り入れつつ企画されています。例えば、ゲーム大会やイベントのアイデアやルールはメンバーで話し合い、決定しています。
            これにより、メンバー全員が楽しめるような企画を行なっています！
        </p>
    </div>

    <!-- 期間内にのみ表示される要素 -->
    <div class="limited-content contact-box">
        <h4>Q. 新入生歓迎会のイベント内容について教えてください。</h4>
    </div>
    <div class="limited-content text">
        <p>
            新入生歓迎会では、4月12日(金)にポケモンSVゆびをふる大会、4月19日(金)にはタイプ統一杯、4月26日(金)にはマルチバトル大会を行います。詳細は<strong><a href="https://toukanomori.hatenablog.com/about" target='_blank' rel='noreferrer noopener' class="new-event">こちら</a></strong>をご覧ください。
        </p>
    </div>

    <div class="contact-box">
        <h4>Q. サークル紹介によると会費が2025年に無料化される予定とのことですが本当ですか？また、その理由について教えてください！</h4>
    </div>
    <div class="text">
        <p>
            はい。会費については2025年に無料化予定です。これはサークルが公認されることにより、大学内の施設を使うことができ、現在の会場である城南市民センターを借りる必要がなくなるためです。これによりメンバー全員がより気軽に参加できる環境を目指しています。
        </p>
    </div>
</div>
</body>
</html>

app/views/touka/about.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'about', media: 'all' %>
  <title>サークル紹介</title>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script>
    $(document).ready(function() {
      var today = new Date();
      var startDate = new Date('2024-01-07');
      var endDate = new Date('2024-04-19');

      if (today >= startDate && today <= endDate) {
        $(".limited-content").show();
      } else {
        $(".limited-content").hide();
      }
    });
  </script>
</head>
<body>

<div class="main-container">
  <div class="page-title">
    <h2><strong>サークル紹介</strong></h2>
  </div>

  <div class="text">
    <h3 class="h3">このサークルについて</h3>
    <p>
      このサークルは、2016年4月に<span style="color: #ff0000;">ポケモンについて語り合いたい</span>という目的で創設されました。
      当サークルは、ポケモン対戦やポケモンカードゲームに興味がある方はもちろん、そうでない方も歓迎します。
      是非一度、部会にお越しください！ <br><br>
      また、当サークルは現在、非公認サークルですが、<span style="color: #ff0000;">2025年公認化予定</span>です！
    </p>

    <h3 class="h3">活動内容について</h3>
    <p>
      ポケモン好きが集まって、ポケモンゲームの対戦やポケモンカードで遊んだりします！また、中にはポケモンだけではなく、スマブラやスプラトゥーンなどをしている人もいます！<br>
      また、定期的に他大学や<strong><a href="https://twitter.com/K_pokeunion" target="_blank" rel="noreferrer noopener" class="new-event">九州ポケサー連盟</a></strong>
      主催の交流会も行っています！<br>
      <strong><span style="color: #ff0000;">会費は部会1回参加あたり、100円です！</span></strong>
      <span class="detail">（2025年に公認化した場合、無料化予定）</span><br>
      他サークルとの掛け持ちでの参加も大歓迎です！(実際に掛け持ちして参加する人もいます！)
    </p>

    <div class="limited-content">
      <h3>新入生歓迎会について</h3>
      <p>
        トウカのもりでは、4月に新入生歓迎会を行います！内容は以下の通りです：<br>
        <div class="event-details">
          4月12日(金) ポケモンSV ゆびをふる大会 <br>
          4月19日(金) ポケモンSV タイプ統一杯 <br>
          4月26日(金) ポケモンSV マルチバトル大会
          <div class="detail">
            ※ポケモンカードは両日程通常の大会を行います。
          </div>
        </div>
        その他、詳しいルールなどの詳細は<strong><a href="https://toukanomori.hatenablog.com/about" target="_blank" rel="noreferrer noopener" class="new-event">こちら</a></strong>をご覧ください。
      </p>
    </div>

    <h3 class="h3">サークルへの加入方法</h3>
    <p>
      サークルへの加入方法は以下の通りです：<br> <br>
      •1 <strong><a href="https://twitter.com/fukudai_pokemon" target='_blank' rel='noreferrer noopener' class="new-event">トウカのもり公式X</a></strong>よりDMで以下を記載し、加入の意思を伝えてください：
      <div class="event-details">
        ・名前(フルネーム)：<br>
        ・学年、学部、学科：<br>
        ・学籍番号：<br>
        ・電話番号：
      </div>
      <p>確認が取れ次第、正式に加入となります！<br><br>
        •2 実際にサークル活動に参加し、トウカのもり代表に加入の意思を伝えてください。
        その後、上記の4項目（名前など）を確認の上、正式に加入となります！
      </p>
    </p>
  </div>
</div>

</body>
</html>

app/views/touka/contact.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'contact', media: 'all' %>
  <title>お問い合わせ</title>
</head>
<body>

<div class="main-container">
    <div class="page-title">
        <h2><strong>お問い合わせ</strong></h2>
    </div>
    <div class="text">
        <br>
        <h3 class="h3">質問・お問い合わせフォーム</h3>
        <p>
            当サークルへのお問い合わせは、他大学様なども含め、以下の方法でお願い致します。<br>
        </p>
    </div>

    <div class="contact-box">
        <h4>◾️メールアドレス</h4>
    </div>
    <div class="text">
        <p>
            toka.pokemon.fukuoka*gmail.com <br>
            ※メールを送る際は、*を@に変えてください。
        </p>
    </div>

    <div class="contact-box">
        <h4>◾️Xアカウント</h4>
    </div>
    <div class="text">
        <p>
            <a href="https://twitter.com/fukudai_pokemon" target='_blank' rel='noreferrer noopener' class="new-event">こちら</a>
            のアカウントのDMよりご連絡ください。
        </p>
    </div>

    <div class="contact-box">
        <h4>◾️質問箱</h4>
    </div>
    <div class="text">
        <p>
            <a href="https://marshmallow-qa.com/2vw324j62ti51he?t=nQwmHX" target='_blank' rel='noreferrer noopener' class="new-event">こちら</a>
            より、ご気軽に質問してください！
        </p>
    </div>

    <div class="text">
        <p>
            ※出来る限り早めに対処しますが、こちらの事情によりすぐに返事が出来ない場合があります。あらかじめご了承下さい。
        </p>
    </div>
</div>
</body>
</html>

app/views/touka/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'index', media: 'all' %>
  <title>ホーム</title>
</head>
<body>

<div class="main-container">
    <div class="main-picture">
        <img src="/assets/main_picture.jpeg" alt="main_picture">
    </div>
    <!-- カレンダーセクション -->
    <div class="calendar">
        <div class="text">
            <strong>部会の日程はこちらをチェック！</strong>
        </div>
        <!-- Google Calendar -->
        <iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=Asia%2FTokyo&showTitle=0&showCalendars=1&showNav=1&src=dG9rYS5wb2tlbW9uLmZ1a3Vva2FAZ21haWwuY29t&src=YWRkcmVzc2Jvb2sjY29udGFjdHNAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&src=amEuamFwYW5lc2UjaG9saWRheUBncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23039BE5&color=%2333B679&color=%230B8043" style="border:solid 1px #777" width="450" height="350" frameborder="0" scrolling="no"></iframe>
    </div>

    <!-- お知らせセクション -->
    <div class="X">
        <div class="text">
            <strong>簡単なお知らせはこちらをチェック！</strong>
        </div>
        <!-- トウカのもり X -->
        <a class="twitter-timeline" data-lang="ja" data-width="375" data-height="500" data-theme="light" href="https://twitter.com/fukudai_pokemon?ref_src=twsrc%5Etfw">Tweets by fukudai_pokemon</a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>

    <!-- 地図セクション -->
    <div class="map">
        <div class="text">
            <p>
                <strong>トウカのもり通常部会の会場はココ！</strong> <br>
                〒814-0142 福岡県福岡市城南区片江5丁目3-25 福岡市立城南市民センター <br>
                3階 第1,2和室 <br>
                <strong>西鉄バス</strong> <br>
                系統番号 12・16「東七隈」下車すぐ <br>
                系統番号 140「七隈四角」下車 徒歩10分 <br>
                <strong>福岡市地下鉄</strong> <br>
                地下鉄七隈線  「七隈駅」下車 徒歩10分
            </p>
        </div>
        <!-- Google Map -->
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3325.0728733187384!2d130.3658810112932!3d33.551482899419675!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x354194750190d421%3A0xc0cc1a289599c9ab!2z56aP5bKh5biC56uLIOWfjuWNl-W4guawkeOCu-ODs-OCv-ODvA!5e0!3m2!1sja!2sjp!4v1703341629245!5m2!1sja!2sjp" width="500" height="500" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>
</body>
</html>

app/views/touka/kyushu_union.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'about', media: 'all' %>
  <title>サークル紹介</title>
</head>
<body>
<div class="main-container">
</div>
</body>

app/views/touka/member.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'member', media: 'all' %>
  <title>サークル紹介</title>
</head>
<body>